### PR TITLE
Catch up with forks

### PR DESCRIPTION
**Pull request by micw**
There are many forks with updates and fixes. I created this PR as a base to catch up with the forks.

### CODE REVIEW

**Comment by egroeper** [comment]
I don't think, that this will work. This repo seems to be dead. Seems like @yosshy has other things to do now.

@yosshy if you don't have time for this, would you accept collaborators for this repo or would you prefer, if some other repo will become the new "upstream" repo?
You did some fine work here and it would be really nice, if there would be one place, where all fixes and tweaks are combined. Without this it is much harder to (re-)use this component.

**Comment by micw** [comment]
@egroeper good point. Re-animating this repo with collaborators would be great because the other forks, especially @locationlabs could provide pull requests as well.

**Comment by yosshy** [comment]
Thqnk you, all.

**Comment by rajatkumar2711** [comment]
@yosshy I have pasted this pacemaker file in 
/usr/lib/python2.7/dist-packages/ansible/module_utils/

and follows Readme.md to write an ansible. 
I have wrote this in my ansible role:

- name: setting up properties
  become: yes
  ignore_target_role: false
  serial: 1
  pacemaker: >
     resource='property no-quorum-policy="ignore" stonith-enabled="false"'
     state=present
  tags:
      - pacemaker-test

I'm getting below error: 

fatal: [**hostname**]: FAILED! => {
    "changed": false, 
    "module_stderr": "Shared connection to "**host_IP**" closed.\r\n", 
    "module_stdout": "\r\n\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_fdnyMu/ansible_module_pacemaker.py\", line 23, in <module>\r\n    from crmsh.xmlutil import xml_equals\r\nImportError: cannot import name xml_equals\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

Can you please let me know why i'm getting this error ?

**Comment by rajatkumar2711** [comment]
@micw  @egroeper  @gnosek  @toabctl @yosshy  
Please share the right procedure to use pacemaker file for ansible module.

**Pull request merged**
